#! /bin/sh

case $1 in
    start)
        /bin/bash /usr/local/bin/javatron-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/javatron-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/javatron-stop.sh
        /bin/bash /usr/local/bin/javatron-start.sh
    ;;
esac
exit 0





